from building import *

cwd = GetCurrentDir()

src = []

if GetDepend('BSP_USING_ETHER'):
    src += ['fsl_phy.c']
    src += ['drv_ether.c']
    src += ['drv_ether2.c']
    src += ['fsl_enet.c']

path =  [cwd]

group = DefineGroup('Ether8720', src, depend = [''], CPPPATH = path)

Return('group')
