from building import *

cwd = GetCurrentDir()

src = []

CPPDEFINES=[]
CPPPATH=[]

if GetDepend('BSP_BOOT_NOR_SDRAM_TXT_SDRAM'):
    
    src += ['../board/xip/fire_imxrt1052_sdram_ini_dcd.c']
    src += ['../board/xip/fire_imxrt1052_spiflash_config.c']
    src += ['../board/xip/fsl_flexspi_nor_boot.c']
    
    CPPPATH = [cwd,cwd + '/../board/xip']
    CPPDEFINES = ['XIP_EXTERNAL_FLASH=1', 'XIP_BOOT_HEADER_ENABLE =1','XIP_BOOT_HEADER_DCD_ENABLE =1','USE_RAM_VECTOR_TABLE']
        
    

group = DefineGroup('Boot', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES=CPPDEFINES)
Return('group')
